In [1]:
import pandas as pd
import numpy as np
from scipy.stats import zscore

In [2]:
df = pd.read_csv('../data/clean_transactions_with_flags.csv')
df.head()

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,...,high_amount_flag,many_login_attempts_flag,long_time_diff_flag,amount_to_balance_ratio,amount_exceeds_balance,suspicious_merchant_flag,reactivation_suspect_flag,duration_suspicious_flag,age_balance_anomaly_flag,strong_anomaly_label
0,469,34,0.037361,2024-11-04 08:06:23,0,29,395,188,99,2,...,0,0,0,0.060637,0,0,0,0,0,0
1,2044,237,0.098158,2024-11-04 08:06:23,1,4,436,24,82,2,...,0,0,0,0.206647,0,0,0,0,0,0
2,1252,455,0.197660,2024-11-04 08:06:23,0,16,648,25,39,1,...,0,0,0,0.235796,0,0,0,0,0,0
3,35,263,0.064883,2024-11-04 08:06:23,1,39,41,479,1,1,...,0,0,0,0.170428,0,0,0,0,0,0
4,2157,153,0.107846,2024-11-04 08:06:23,1,8,586,340,27,2,...,0,0,0,0.200754,0,1,0,0,0,1

In [3]:
df.columns

Index(['TransactionID', 'AccountID', 'TransactionAmount', 'TransactionDate',
       'TransactionType', 'Location', 'DeviceID', 'IP Address', 'MerchantID',
       'Channel', 'CustomerAge', 'CustomerOccupation', 'TransactionDuration',
       'LoginAttempts', 'AccountBalance', 'PreviousTransactionDate',
       'time_diff', 'location_change', 'Hour', 'Day', 'DayOfWeek',
       'high_amount_flag', 'many_login_attempts_flag', 'long_time_diff_flag',
       'amount_to_balance_ratio', 'amount_exceeds_balance',
       'suspicious_merchant_flag', 'reactivation_suspect_flag',
       'duration_suspicious_flag', 'age_balance_anomaly_flag',
       'strong_anomaly_label'],
      dtype='object')

In [4]:
selected_columns_for_zscore = [
    'TransactionAmount',
    'TransactionDuration',
    'LoginAttempts',
    'AccountBalance',
    'time_diff',
    'Hour',
    'Day',
    'amount_to_balance_ratio'
]

In [5]:
z_scores = df[selected_columns_for_zscore].apply(zscore)
z_scores.columns = ['zscore_' + col for col in selected_columns_for_zscore]

In [6]:
z_flags = (z_scores.abs() > 3).astype(int)
z_flags.columns = ['flag_zscore_' + col for col in selected_columns_for_zscore]

In [7]:
df_zscore = pd.concat([df, z_scores, z_flags], axis=1)

In [8]:
df_zscore.head()

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,...,zscore_Day,zscore_amount_to_balance_ratio,flag_zscore_TransactionAmount,flag_zscore_TransactionDuration,flag_zscore_LoginAttempts,flag_zscore_AccountBalance,flag_zscore_time_diff,flag_zscore_Hour,flag_zscore_Day,flag_zscore_amount_to_balance_ratio
0,469,34,0.037361,2024-11-04 08:06:23,0,29,395,188,99,2,...,NaN,-0.039210,0,0,0,0,0,0,0,0
1,2044,237,0.098158,2024-11-04 08:06:23,1,4,436,24,82,2,...,NaN,-0.038574,0,0,0,0,0,0,0,0
2,1252,455,0.197660,2024-11-04 08:06:23,0,16,648,25,39,1,...,NaN,-0.038446,0,0,0,0,0,0,0,0
3,35,263,0.064883,2024-11-04 08:06:23,1,39,41,479,1,1,...,NaN,-0.038731,0,0,0,0,0,0,0,0
4,2157,153,0.107846,2024-11-04 08:06:23,1,8,586,340,27,2,...,NaN,-0.038599,0,0,0,0,0,0,0,0

In [9]:
df_zscore.columns

Index(['TransactionID', 'AccountID', 'TransactionAmount', 'TransactionDate',
       'TransactionType', 'Location', 'DeviceID', 'IP Address', 'MerchantID',
       'Channel', 'CustomerAge', 'CustomerOccupation', 'TransactionDuration',
       'LoginAttempts', 'AccountBalance', 'PreviousTransactionDate',
       'time_diff', 'location_change', 'Hour', 'Day', 'DayOfWeek',
       'high_amount_flag', 'many_login_attempts_flag', 'long_time_diff_flag',
       'amount_to_balance_ratio', 'amount_exceeds_balance',
       'suspicious_merchant_flag', 'reactivation_suspect_flag',
       'duration_suspicious_flag', 'age_balance_anomaly_flag',
       'strong_anomaly_label', 'zscore_TransactionAmount',
       'zscore_TransactionDuration', 'zscore_LoginAttempts',
       'zscore_AccountBalance', 'zscore_time_diff', 'zscore_Hour',
       'zscore_Day', 'zscore_amount_to_balance_ratio',
       'flag_zscore_TransactionAmount', 'flag_zscore_TransactionDuration',
       'flag_zscore_LoginAttempts', 'flag_zscore_AccountBalance',
       'flag_zscore_time_diff', 'flag_zscore_Hour', 'flag_zscore_Day',
       'flag_zscore_amount_to_balance_ratio'],
      dtype='object')

In [10]:
df_zscore.describe()

,TransactionID,AccountID,TransactionAmount,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,...,zscore_Day,zscore_amount_to_balance_ratio,flag_zscore_TransactionAmount,flag_zscore_TransactionDuration,flag_zscore_LoginAttempts,flag_zscore_AccountBalance,flag_zscore_time_diff,flag_zscore_Hour,flag_zscore_Day,flag_zscore_amount_to_balance_ratio
count,2512.000000,2512.000000,2512.000000,2512.000000,2512.000000,2512.000000,2512.000000,2512.000000,2512.000000,2512.000000,...,0.0,2.512000e+03,2512.000000,2512.0,2512.000000,2512.0,2512.000000,2512.0,2512.0,2512.000000
mean,1255.500000,246.637739,0.154954,0.773885,21.032643,337.732882,297.083201,48.523885,0.991242,0.430225,...,NaN,9.192930e-18,0.019108,0.0,0.037818,0.0,0.000398,0.0,0.0,0.001194
std,725.296261,143.353390,0.152146,0.418398,12.253549,198.210671,169.659435,29.032470,0.809100,0.286971,...,NaN,1.000199e+00,0.136933,0.0,0.190795,0.0,0.019952,0.0,0.0,0.034544
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,-3.947488e-02,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
25%,627.750000,123.000000,0.042538,1.000000,11.000000,166.750000,150.000000,24.000000,0.000000,0.145161,...,NaN,-3.884623e-02,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
50%,1255.500000,250.000000,0.109899,1.000000,21.000000,335.500000,294.000000,48.000000,1.000000,0.435484,...,NaN,-3.767820e-02,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
75%,1883.250000,369.000000,0.215894,1.000000,31.000000,510.000000,447.000000,73.000000,2.000000,0.661290,...,NaN,-3.403916e-02,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
max,2511.000000,494.000000,1.000000,1.000000,42.000000,680.000000,591.000000,99.000000,2.000000,1.000000,...,NaN,4.329613e+01,1.000000,0.0,1.000000,0.0,1.000000,0.0,0.0,1.000000

In [11]:
df_zscore.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2512 entries, 0 to 2511
Data columns (total 47 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   TransactionID                        2512 non-null   int64
 1   AccountID                            2512 non-null   int64
 2   TransactionAmount                    2512 non-null   float64
 3   TransactionDate                      2512 non-null   object
 4   TransactionType                      2512 non-null   int64
 5   Location                             2512 non-null   int64
 6   DeviceID                             2512 non-null   int64
 7   IP Address                           2512 non-null   int64
 8   MerchantID                           2512 non-null   int64
 9   Channel                              2512 non-null   int64
 10  CustomerAge                          2512 non-null   float64
 11  CustomerOccupation                   2512 non-null   int64
 12  TransactionDuration                  2512 non-null   float64
 13  LoginAttempts                        2512 non-null   float64
 14  AccountBalance                       2512 non-null   float64
 15  PreviousTransactionDate              2512 non-null   object
 16  time_diff                            2512 non-null   float64
 17  location_change                      2512 non-null   int64
 18  Hour                                 2512 non-null   int64
 19  Day                                  2512 non-null   int64
 20  DayOfWeek                            2512 non-null   int64
 21  high_amount_flag                     2512 non-null   int64
 22  many_login_attempts_flag             2512 non-null   int64
 23  long_time_diff_flag                  2512 non-null   int64
 24  amount_to_balance_ratio              2512 non-null   float64
 25  amount_exceeds_balance               2512 non-null   int64
 26  suspicious_merchant_flag             2512 non-null   int64
 27  reactivation_suspect_flag            2512 non-null   int64
 28  duration_suspicious_flag             2512 non-null   int64
 29  age_balance_anomaly_flag             2512 non-null   int64
 30  strong_anomaly_label                 2512 non-null   int64
 31  zscore_TransactionAmount             2512 non-null   float64
 32  zscore_TransactionDuration           2512 non-null   float64
 33  zscore_LoginAttempts                 2512 non-null   float64
 34  zscore_AccountBalance                2512 non-null   float64
 35  zscore_time_diff                     2512 non-null   float64
 36  zscore_Hour                          0 non-null      float64
 37  zscore_Day                           0 non-null      float64
 38  zscore_amount_to_balance_ratio       2512 non-null   float64
 39  flag_zscore_TransactionAmount        2512 non-null   int64
 40  flag_zscore_TransactionDuration      2512 non-null   int64
 41  flag_zscore_LoginAttempts            2512 non-null   int64
 42  flag_zscore_AccountBalance           2512 non-null   int64
 43  flag_zscore_time_diff                2512 non-null   int64
 44  flag_zscore_Hour                     2512 non-null   int64
 45  flag_zscore_Day                      2512 non-null   int64
 46  flag_zscore_amount_to_balance_ratio  2512 non-null   int64
dtypes: float64(15), int64(30), object(2)
memory usage: 922.5+ KB

In [12]:
df_zscore.to_csv("../data/transactions_with_zscores.csv", index=False)